services:
    jenkins:
        image: jenkins/jenkins:lts-jdk17
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        healthcheck:
            test: ["CMD", "curl", "-f", "http://jenkins:8080/login"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: on-failure
              
volumes:
    jenkins_home:
